# Generated by Django 3.2.9 on 2022-06-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='PRinformation',
            field=models.TextField(blank=True, null=True, verbose_name='Information'),
        ),
    ]
