# Generated by Django 3.2.9 on 2022-06-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_prinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='qunatity',
            field=models.IntegerField(default=0),
        ),
    ]
