# Generated by Django 3.2.9 on 2022-09-02 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_alter_order_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crowd_Funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Title')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Details')),
                ('total_target', models.IntegerField(blank=True, null=True, verbose_name='Total_Target')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Crowd Funding',
                'verbose_name_plural': 'Crowd Funding',
            },
        ),
    ]
